package fixture

import (
	"ciphera/tools/internal/contract"
	"ciphera/tools/internal/policy"
	"ciphera/tools/internal/requirementid"
)

const (
	// Target is the primary target fixture.
	Target = "test_target"
	// OtherTarget is the secondary target fixture.
	OtherTarget = "other_target"
	// FileSet is the default file set fixture.
	FileSet = "test_files"
	// Language is the default language fixture.
	Language = "test"
	// PathRole is the default path role fixture.
	PathRole = "test_paths"
	// Requirement is the default requirement ID fixture.
	Requirement = "1.1." + "test-rule"
	// Rule is the default rule ID fixture.
	Rule = "test/rule"
	// Scope is the default repository scope fixture.
	Scope = contract.Scope("test")
	// Tool is the default tool ID fixture.
	Tool = "test/tool"
)

/* -------------------------------------- Profile Fixtures -------------------------------------- */

// Config returns a valid minimal profile config fixture.
func Config() (config policy.Config) {
	return policy.Config{
		SchemaVersion: policy.SchemaVersion,
		Repository:    baselineRepository(),
		StyleGuide: policy.StyleGuideConfig{
			Path:     "STYLE.md",
			IDScheme: requirementid.SectionSlug,
		},
		PathRoles: policy.PathRoles{
			PathRole: {"internal/"},
		},
		FileSets:     baselineFileSets(),
		Targets:      baselineTargets(),
		Tools:        baselineTools(),
		EnabledPacks: []string{"test"},
		Rules: []policy.RuleBinding{
			{
				RuleID:         Rule,
				Enforcement:    contract.EnforcementRequired,
				Scope:          Scope,
				RequirementIDs: []string{Requirement},
			},
		},
	}
}

func baselineRepository() (repository policy.RepositoryConfig) {
	return policy.RepositoryConfig{
		RootMarkers: []string{
			"PROJECT.marker",
		},
		ScopeRoots: map[contract.Scope][]string{
			Scope: {"."},
		},
		DefaultScope:    Scope,
		GeneratedMarker: "Code generated by",
	}
}

func baselineFileSets() (fileSets policy.FileSets) {
	return append(fileSets, policy.FileSetConfig{
		Name: FileSet,
		Include: policy.FileSetInclude{
			Extensions: []string{".go"},
			Paths: map[contract.Scope][]string{
				Scope: {"internal/"},
			},
		},
	})
}

func baselineTargets() (targets policy.TargetConfigs) {
	return append(targets,
		policy.TargetConfig{
			Name:        Target,
			Language:    Language,
			Scope:       Scope,
			FormatPaths: []string{"."},
			CheckPaths:  []string{"."},
		},
		policy.TargetConfig{
			Name:        OtherTarget,
			Language:    Language,
			Scope:       Scope,
			FormatPaths: []string{"."},
			CheckPaths:  []string{"."},
		},
	)
}

func baselineTools() (tools policy.PinnedTools) {
	return append(tools, policy.PinnedTool{ID: Tool, Version: "1.0.0"})
}

// Definitions returns rule and tool definitions that match Config.
func Definitions() (definitions contract.Definitions) {
	return contract.Definitions{
		Tools: []contract.Tool{
			{ID: Tool, Name: "Test tool"},
		},
		Rules: []contract.RuleDefinition{
			{
				ID:    Rule,
				Name:  "Test rule",
				Group: "test",
				Check: contract.ExecutionSpec{
					Kind: contract.ExecutorRepositoryScan,
					Detail: contract.RepositoryScanExecution{
						Scanner: "test",
					},
				},
			},
		},
	}
}

// FileCommandDefinitions returns definitions with a file-command rule.
func FileCommandDefinitions() (definitions contract.Definitions) {
	definitions = Definitions()
	definitions.Rules[0].Check = contract.ExecutionSpec{
		Kind: contract.ExecutorFileCommand,
		Detail: contract.FileCommandExecution{
			ToolID:  Tool,
			FileSet: FileSet,
		},
	}
	return definitions
}

// TargetCommandDefinitions returns definitions with target check and fix executions.
func TargetCommandDefinitions() (definitions contract.Definitions) {
	definitions = Definitions()
	definitions.Rules[0].Check = contract.ExecutionSpec{
		Kind: contract.ExecutorTargetCommand,
		Detail: contract.TargetCommandExecution{
			ToolIDs:  []string{Tool},
			Action:   "test",
			Language: Language,
		},
	}
	definitions.Rules[0].Fix = contract.ExecutionSpec{
		Kind: contract.ExecutorTargetCommand,
		Detail: contract.TargetCommandExecution{
			ToolIDs:  []string{Tool},
			Action:   "fix",
			Language: Language,
		},
	}
	return definitions
}

// TargetCheckDefinitions returns definitions with a target check execution.
func TargetCheckDefinitions() (definitions contract.Definitions) {
	definitions = Definitions()
	definitions.Rules[0].Check = contract.ExecutionSpec{
		Kind: contract.ExecutorTargetCheck,
		Detail: contract.TargetCheckExecution{
			ToolIDs:  []string{Tool},
			Check:    "test",
			Language: Language,
		},
	}
	return definitions
}
