package architecture

/* ------------------------------------- Platform Boundaries ------------------------------------ */

func platformBoundaryCases() (testCases []importBoundaryCase) {
	return []importBoundaryCase{
		{
			name:      "contract does not import internal packages",
			directory: "internal/contract",
			forbidden: []string{"ciphera/tools/internal/"},
		},
		{
			name:      "profile avoids runtime implementation packages",
			directory: "internal/profile",
			forbidden: []string{
				"ciphera/tools/internal/installer",
				"ciphera/tools/internal/runner/drivers",
				"ciphera/tools/internal/report",
				"ciphera/tools/internal/pack/builtin",
				"ciphera/tools/internal/runner",
			},
		},
		{
			name:      "profile TOML codec depends only on profile policy types",
			directory: "internal/profile/toml",
			forbidden: []string{
				"ciphera/tools/internal/cli",
				"ciphera/tools/internal/coverage",
				"ciphera/tools/internal/runner/drivers",
				"ciphera/tools/internal/filewalk",
				"ciphera/tools/internal/installer",
				"ciphera/tools/internal/profile",
				"ciphera/tools/internal/report",
				"ciphera/tools/internal/pack/builtin",
				"ciphera/tools/internal/runner",
				"ciphera/tools/internal/rules",
				"ciphera/tools/internal/runtime",
				"ciphera/tools/internal/styleguide",
				"ciphera/tools/internal/toolchain",
			},
		},
		{
			name:      "profile validation depends only on policy and contracts",
			directory: "internal/profile/validation",
			forbidden: []string{
				"ciphera/tools/internal/cli",
				"ciphera/tools/internal/coverage",
				"ciphera/tools/internal/runner/drivers",
				"ciphera/tools/internal/filewalk",
				"ciphera/tools/internal/installer",
				"ciphera/tools/internal/profile",
				"ciphera/tools/internal/report",
				"ciphera/tools/internal/pack/builtin",
				"ciphera/tools/internal/runner",
				"ciphera/tools/internal/rules",
				"ciphera/tools/internal/runtime",
				"ciphera/tools/internal/styleguide",
				"ciphera/tools/internal/toolchain",
			},
		},
		{
			name:      "profile effective compiler may use pack definitions",
			directory: "internal/profile/effective",
			forbidden: []string{
				"ciphera/tools/internal/cli",
				"ciphera/tools/internal/coverage",
				"ciphera/tools/internal/runner/drivers",
				"ciphera/tools/internal/filewalk",
				"ciphera/tools/internal/installer",
				"ciphera/tools/internal/profile",
				"ciphera/tools/internal/report",
				"ciphera/tools/internal/runner",
				"ciphera/tools/internal/rules",
				"ciphera/tools/internal/runtime",
				"ciphera/tools/internal/styleguide",
				"ciphera/tools/internal/toolchain",
			},
		},
		{
			name:      "policy depends only on contracts",
			directory: "internal/policy",
			forbidden: []string{
				"ciphera/tools/internal/cli",
				"ciphera/tools/internal/coverage",
				"ciphera/tools/internal/runner/drivers",
				"ciphera/tools/internal/filewalk",
				"ciphera/tools/internal/installer",
				"ciphera/tools/internal/profile",
				"ciphera/tools/internal/report",
				"ciphera/tools/internal/pack/builtin",
				"ciphera/tools/internal/runner",
				"ciphera/tools/internal/rules",
				"ciphera/tools/internal/runtime",
				"ciphera/tools/internal/styleguide",
			},
		},
		{
			name:      "pack definitions avoid Shipped Pack implementations",
			directory: "internal/pack",
			forbidden: []string{
				"ciphera/tools/internal/architecture",
				"ciphera/tools/internal/cli",
				"ciphera/tools/internal/coverage",
				"ciphera/tools/internal/runner/drivers",
				"ciphera/tools/internal/filewalk",
				"ciphera/tools/internal/installer",
				"ciphera/tools/internal/profile",
				"ciphera/tools/internal/report",
				"ciphera/tools/internal/pack/builtin",
				"ciphera/tools/internal/runner",
				"ciphera/tools/internal/rules",
				"ciphera/tools/internal/runtime",
				"ciphera/tools/internal/styleguide",
			},
		},
		{
			name:      "runner is generic execution machinery",
			directory: "internal/runner",
			forbidden: []string{
				"ciphera/tools/internal/installer",
				"ciphera/tools/internal/profile",
				"ciphera/tools/internal/report",
				"ciphera/tools/internal/pack/builtin",
				"ciphera/tools/internal/runner/drivers",
				"ciphera/tools/internal/runtime",
			},
		},
		{
			name:      "runtime avoids policy and installation orchestration",
			directory: "internal/runtime",
			forbidden: []string{
				"ciphera/tools/internal/cli",
				"ciphera/tools/internal/coverage",
				"ciphera/tools/internal/filewalk",
				"ciphera/tools/internal/installer",
				"ciphera/tools/internal/policy",
				"ciphera/tools/internal/profile",
				"ciphera/tools/internal/report",
				"ciphera/tools/internal/pack/builtin",
				"ciphera/tools/internal/runner",
				"ciphera/tools/internal/rules",
				"ciphera/tools/internal/styleguide",
			},
		},
		{
			name:      "installer depends only on runtime and tool contracts",
			directory: "internal/installer",
			forbidden: []string{
				"ciphera/tools/internal/cli",
				"ciphera/tools/internal/coverage",
				"ciphera/tools/internal/filewalk",
				"ciphera/tools/internal/policy",
				"ciphera/tools/internal/profile",
				"ciphera/tools/internal/report",
				"ciphera/tools/internal/pack/builtin",
				"ciphera/tools/internal/runner",
				"ciphera/tools/internal/rules",
				"ciphera/tools/internal/styleguide",
			},
		},
		{
			name:      "runner drivers avoid profile, report, and installation concerns",
			directory: "internal/runner/drivers",
			forbidden: []string{
				"ciphera/tools/internal/cli",
				"ciphera/tools/internal/coverage",
				"ciphera/tools/internal/installer",
				"ciphera/tools/internal/profile",
				"ciphera/tools/internal/report",
				"ciphera/tools/internal/styleguide",
			},
		},
		{
			name:      "toolchain depends only on contracts",
			directory: "internal/toolchain",
			forbidden: []string{
				"ciphera/tools/internal/architecture",
				"ciphera/tools/internal/cli",
				"ciphera/tools/internal/coverage",
				"ciphera/tools/internal/runner/drivers",
				"ciphera/tools/internal/filewalk",
				"ciphera/tools/internal/installer",
				"ciphera/tools/internal/policy",
				"ciphera/tools/internal/profile",
				"ciphera/tools/internal/report",
				"ciphera/tools/internal/pack/builtin",
				"ciphera/tools/internal/runner",
				"ciphera/tools/internal/rules",
				"ciphera/tools/internal/runtime",
				"ciphera/tools/internal/styleguide",
			},
		},
		{
			name:      "shipped Pack modules avoid execution orchestration",
			directory: "internal/pack/builtin",
			recursive: true,
			forbidden: []string{
				"ciphera/tools/internal/architecture",
				"ciphera/tools/internal/cli",
				"ciphera/tools/internal/coverage",
				"ciphera/tools/internal/runner/drivers",
				"ciphera/tools/internal/filewalk",
				"ciphera/tools/internal/installer",
				"ciphera/tools/internal/profile",
				"ciphera/tools/internal/report",
				"ciphera/tools/internal/runner",
				"ciphera/tools/internal/runtime",
				"ciphera/tools/internal/styleguide",
			},
		},
		{
			name:      "filewalk does not import profile",
			directory: "internal/filewalk",
			forbidden: []string{
				"ciphera/tools/internal/profile",
			},
		},
		{
			name:      "styleguide does not import profile or Shipped Packs",
			directory: "internal/styleguide",
			forbidden: []string{
				"ciphera/tools/internal/profile",
				"ciphera/tools/internal/pack/builtin",
			},
		},
	}
}
