package architecture

/* ------------------------------------- Platform Boundaries ------------------------------------ */

func platformBoundaryCases() (testCases []importBoundaryCase) {
	return []importBoundaryCase{
		{
			name:      "style vocabulary does not import internal packages",
			directory: "internal/style",
			forbidden: []string{"ciphera/tools/internal/"},
		},
		{
			name:      "profile avoids runtime implementation packages",
			directory: "internal/profile",
			forbidden: []string{
				"ciphera/tools/internal/installer",
				"ciphera/tools/internal/runner/drivers",
				"ciphera/tools/internal/report",
				"ciphera/tools/internal/pack/shipped",
				"ciphera/tools/internal/runner",
			},
		},
		{
			name:      "profile TOML codec depends only on profile policy types",
			directory: "internal/profile/toml",
			forbidden: []string{
				"ciphera/tools/internal/cli",
				"ciphera/tools/internal/coverage",
				"ciphera/tools/internal/runner/drivers",
				"ciphera/tools/internal/filewalk",
				"ciphera/tools/internal/installer",
				"ciphera/tools/internal/profile",
				"ciphera/tools/internal/report",
				"ciphera/tools/internal/pack/shipped",
				"ciphera/tools/internal/runner",
				"ciphera/tools/internal/checks",
				"ciphera/tools/internal/runtime",
				"ciphera/tools/internal/styleguide",
				"ciphera/tools/internal/toolchain",
			},
		},
		{
			name:      "profile validation depends only on policy and style vocabulary",
			directory: "internal/profile/internal/validation",
			forbidden: []string{
				"ciphera/tools/internal/cli",
				"ciphera/tools/internal/coverage",
				"ciphera/tools/internal/runner/drivers",
				"ciphera/tools/internal/filewalk",
				"ciphera/tools/internal/installer",
				"ciphera/tools/internal/profile",
				"ciphera/tools/internal/report",
				"ciphera/tools/internal/pack/shipped",
				"ciphera/tools/internal/runner",
				"ciphera/tools/internal/checks",
				"ciphera/tools/internal/runtime",
				"ciphera/tools/internal/styleguide",
				"ciphera/tools/internal/toolchain",
			},
		},
		{
			name:      "profile effective compiler may use pack definitions",
			directory: "internal/profile/internal/effective",
			forbidden: []string{
				"ciphera/tools/internal/cli",
				"ciphera/tools/internal/coverage",
				"ciphera/tools/internal/runner/drivers",
				"ciphera/tools/internal/filewalk",
				"ciphera/tools/internal/installer",
				"ciphera/tools/internal/profile",
				"ciphera/tools/internal/report",
				"ciphera/tools/internal/runner",
				"ciphera/tools/internal/checks",
				"ciphera/tools/internal/runtime",
				"ciphera/tools/internal/styleguide",
				"ciphera/tools/internal/toolchain",
			},
		},
		{
			name:      "policy depends only on style vocabulary",
			directory: "internal/policy",
			forbidden: []string{
				"ciphera/tools/internal/cli",
				"ciphera/tools/internal/coverage",
				"ciphera/tools/internal/runner/drivers",
				"ciphera/tools/internal/filewalk",
				"ciphera/tools/internal/installer",
				"ciphera/tools/internal/profile",
				"ciphera/tools/internal/report",
				"ciphera/tools/internal/pack/shipped",
				"ciphera/tools/internal/runner",
				"ciphera/tools/internal/checks",
				"ciphera/tools/internal/runtime",
				"ciphera/tools/internal/styleguide",
			},
		},
		{
			name:      "pack definitions avoid Shipped Pack implementations",
			directory: "internal/pack",
			forbidden: []string{
				"ciphera/tools/internal/architecture",
				"ciphera/tools/internal/cli",
				"ciphera/tools/internal/coverage",
				"ciphera/tools/internal/runner/drivers",
				"ciphera/tools/internal/filewalk",
				"ciphera/tools/internal/installer",
				"ciphera/tools/internal/profile",
				"ciphera/tools/internal/report",
				"ciphera/tools/internal/pack/shipped",
				"ciphera/tools/internal/runner",
				"ciphera/tools/internal/checks",
				"ciphera/tools/internal/runtime",
				"ciphera/tools/internal/styleguide",
			},
		},
		{
			name:      "runner is generic execution machinery",
			directory: "internal/runner",
			forbidden: []string{
				"ciphera/tools/internal/installer",
				"ciphera/tools/internal/profile",
				"ciphera/tools/internal/report",
				"ciphera/tools/internal/pack/shipped",
				"ciphera/tools/internal/runner/drivers",
				"ciphera/tools/internal/runtime",
			},
		},
		{
			name:      "runtime avoids policy and installation orchestration",
			directory: "internal/runtime",
			forbidden: []string{
				"ciphera/tools/internal/cli",
				"ciphera/tools/internal/coverage",
				"ciphera/tools/internal/filewalk",
				"ciphera/tools/internal/installer",
				"ciphera/tools/internal/policy",
				"ciphera/tools/internal/profile",
				"ciphera/tools/internal/report",
				"ciphera/tools/internal/pack/shipped",
				"ciphera/tools/internal/runner",
				"ciphera/tools/internal/checks",
				"ciphera/tools/internal/styleguide",
			},
		},
		{
			name:      "installer depends only on runtime and style tool types",
			directory: "internal/installer",
			forbidden: []string{
				"ciphera/tools/internal/cli",
				"ciphera/tools/internal/coverage",
				"ciphera/tools/internal/filewalk",
				"ciphera/tools/internal/policy",
				"ciphera/tools/internal/profile",
				"ciphera/tools/internal/report",
				"ciphera/tools/internal/pack/shipped",
				"ciphera/tools/internal/runner",
				"ciphera/tools/internal/checks",
				"ciphera/tools/internal/styleguide",
			},
		},
		{
			name:      "runner drivers avoid shipped, profile, report, and installation concerns",
			directory: "internal/runner/drivers",
			forbidden: []string{
				"ciphera/tools/internal/cli",
				"ciphera/tools/internal/coverage",
				"ciphera/tools/internal/installer",
				"ciphera/tools/internal/profile",
				"ciphera/tools/internal/report",
				"ciphera/tools/internal/styleguide",
				"ciphera/tools/internal/pack/shipped",
			},
		},
		{
			name:      "toolchain depends only on runtime and toolchain vocabulary",
			directory: "internal/toolchain",
			forbidden: []string{
				"ciphera/tools/internal/architecture",
				"ciphera/tools/internal/cli",
				"ciphera/tools/internal/coverage",
				"ciphera/tools/internal/runner/drivers",
				"ciphera/tools/internal/filewalk",
				"ciphera/tools/internal/installer",
				"ciphera/tools/internal/policy",
				"ciphera/tools/internal/profile",
				"ciphera/tools/internal/report",
				"ciphera/tools/internal/pack/shipped",
				"ciphera/tools/internal/runner",
				"ciphera/tools/internal/checks",
				"ciphera/tools/internal/styleguide",
			},
		},
		{
			name:      "shipped Pack catalogue avoids execution orchestration",
			directory: "internal/pack/shipped",
			forbidden: []string{
				"ciphera/tools/internal/architecture",
				"ciphera/tools/internal/cli",
				"ciphera/tools/internal/coverage",
				"ciphera/tools/internal/runner/drivers",
				"ciphera/tools/internal/filewalk",
				"ciphera/tools/internal/installer",
				"ciphera/tools/internal/profile",
				"ciphera/tools/internal/report",
				"ciphera/tools/internal/runner",
				"ciphera/tools/internal/runtime",
				"ciphera/tools/internal/styleguide",
			},
		},
		{
			name:      "shipped runtime bindings import only driver facade",
			directory: "internal/pack/shipped/bindings",
			forbidden: []string{
				"ciphera/tools/internal/architecture",
				"ciphera/tools/internal/cli",
				"ciphera/tools/internal/coverage",
				"ciphera/tools/internal/runner/drivers/command",
				"ciphera/tools/internal/runner/drivers/internal",
				"ciphera/tools/internal/runner/drivers/profile",
				"ciphera/tools/internal/runner/drivers/scan",
				"ciphera/tools/internal/runner/drivers/target",
				"ciphera/tools/internal/filewalk",
				"ciphera/tools/internal/installer",
				"ciphera/tools/internal/profile",
				"ciphera/tools/internal/report",
				"ciphera/tools/internal/runtime",
				"ciphera/tools/internal/styleguide",
			},
		},
		{
			name:      "filewalk does not import profile",
			directory: "internal/filewalk",
			forbidden: []string{
				"ciphera/tools/internal/profile",
			},
		},
		{
			name:      "styleguide does not import profile or Shipped Packs",
			directory: "internal/styleguide",
			forbidden: []string{
				"ciphera/tools/internal/profile",
				"ciphera/tools/internal/pack/shipped",
			},
		},
	}
}
