package scenarios

import (
	"path/filepath"
	"testing"

	"github.com/wbd2023/Quill/internal/checks/golang"
	"github.com/wbd2023/Quill/internal/testutil"
	"github.com/wbd2023/Quill/internal/testutil/profiles"
)

func TestGoStyleRejectsMissingScanRoot(t *testing.T) {
	missingRoot := filepath.Join(t.TempDir(), "missing")
	config := profiles.Current(t)

	if _, err := golang.CheckDirectories(
		testutil.RepositoryRoot(t),
		[]string{missingRoot},
		config.Repository,
		config.PathRoles,
		goConfigForTest(t, config),
	); err == nil {
		t.Fatal("expected missing scan root error")
	}
}

func TestGoStyleSkipsGeneratedFiles(t *testing.T) {
	tempDir := t.TempDir()
	writeSourceFile(
		t,
		filepath.Join(tempDir, "internal", "generated.go"),
		`// Code generated by test. DO NOT EDIT.
package internal

func Bad() string {
	return ""
}
`,
	)

	result, err := runGoStyleResult(t, tempDir)
	if err != nil {
		t.Fatalf("expected generated Go file to be skipped, diagnostics: %#v", result.Diagnostics)
	}
}
