package filewalk

import (
	"os"
	"path/filepath"
	"slices"
	"testing"

	"github.com/wbd2023/quill/internal/profile"
	"github.com/wbd2023/quill/internal/style"
	"github.com/wbd2023/quill/internal/testutil"
	"github.com/wbd2023/quill/internal/testutil/profiles"
)

/* --------------------------------------- File Collection -------------------------------------- */

func TestCollectFilesSkipsExcludedDirectoriesAndGeneratedFiles(t *testing.T) {
	root := t.TempDir()
	keptFile := testutil.WriteFile(t, root, "internal/example/kept.go", "package example\n")
	testdataFile := testutil.WriteFile(
		t,
		root,
		"testdata/example/skipped.go",
		"package example\n",
	)
	thirdPartyFile := testutil.WriteFile(
		t,
		root,
		"third_party/example/skipped.go",
		"package example\n",
	)
	generatedFile := testutil.WriteFile(
		t,
		root,
		"internal/example/generated.go",
		"// Code generated by tests. DO NOT EDIT.\npackage example\n",
	)

	repository := profiles.RepositoryConfig()
	files, err := CollectFiles(
		repository.ResolveScopeRoots(root, style.Scope("all")),
		walkConfig(repository),
		".go",
	)
	if err != nil {
		t.Fatalf("collect files: %v", err)
	}

	if !slices.Contains(files, keptFile) {
		t.Fatalf("expected kept file %q in %v", keptFile, files)
	}

	for _, path := range files {
		switch path {
		case testdataFile, thirdPartyFile, generatedFile:
			t.Fatalf("unexpected excluded file %q in %v", path, files)
		}
	}
}

func TestCollectFilesKeepsProseMentionsOfGeneratedMarker(t *testing.T) {
	root := t.TempDir()
	markdownFile := testutil.WriteFile(
		t,
		root,
		"STYLE.md",
		"# Style guide\n\n* Generated files that include `DO NOT EDIT.`\n",
	)

	repository := profiles.RepositoryConfig()
	files, err := CollectFiles(
		repository.ResolveScopeRoots(root, style.Scope("all")),
		walkConfig(repository),
		".md",
	)
	if err != nil {
		t.Fatalf("collect markdown files: %v", err)
	}

	if !slices.Contains(files, markdownFile) {
		t.Fatalf("expected prose markdown file %q in %v", markdownFile, files)
	}
}

func TestCollectFilesDeduplicatesOverlappingRoots(t *testing.T) {
	root := t.TempDir()
	commandFile := testutil.WriteFile(t, root, "cmd/main.go", "package main\n")
	internalFile := testutil.WriteFile(t, root, "internal/app.go", "package internal\n")
	toolsFile := testutil.WriteFile(t, root, "tools/main.go", "package main\n")

	repository := profiles.RepositoryConfig()
	roots := []string{
		filepath.Join(root, "cmd"),
		filepath.Join(root, "internal"),
		filepath.Join(root, "tools"),
	}
	files, err := CollectFiles(roots, walkConfig(repository), ".go")
	if err != nil {
		t.Fatalf("collect scoped files: %v", err)
	}

	requirePaths(t, files, []string{commandFile, internalFile, toolsFile})
}

func TestCollectFilesWithoutExtensionsCollectsOnlyRegularFiles(t *testing.T) {
	root := t.TempDir()
	regular := testutil.WriteFile(t, root, "regular.go", "package regular\n")
	directory := filepath.Join(root, "directory")
	if err := os.MkdirAll(directory, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink(directory, filepath.Join(root, "directory.go")); err != nil {
		t.Skipf("symlink unsupported: %v", err)
	}

	files, err := CollectFiles([]string{root}, walkConfig(profiles.RepositoryConfig()))
	if err != nil {
		t.Fatalf("CollectFiles: %v", err)
	}

	requirePaths(t, files, []string{regular})
}

func TestCollectAllFilesKeepsConfigMentionsOfGeneratedMarker(t *testing.T) {
	root := t.TempDir()
	configFile := testutil.WriteFile(
		t,
		root,
		"quill.toml",
		"generated_marker = \"DO NOT EDIT.\"\n",
	)

	repository := profiles.RepositoryConfig()
	files, err := CollectAllFiles(
		repository.ResolveScopeRoots(root, style.Scope("all")),
		walkConfig(repository),
	)
	if err != nil {
		t.Fatalf("collect all files: %v", err)
	}

	if !slices.Contains(files, configFile) {
		t.Fatalf("expected config file %q in %v", configFile, files)
	}
}

func TestCollectAllFilesExcludesGitAdministrativeFile(t *testing.T) {
	root := t.TempDir()
	kept := testutil.WriteFile(t, root, "kept.txt", "kept\n")
	testutil.WriteFile(t, root, ".git", "gitdir: /tmp/repository.git/worktrees/main\n")

	repository := profiles.RepositoryConfig()
	files, err := CollectAllFiles(
		repository.ResolveScopeRoots(root, style.Scope("all")),
		walkConfig(repository),
	)
	if err != nil {
		t.Fatalf("collect all files: %v", err)
	}

	requirePaths(t, files, []string{kept})
}

func TestCollectAllFilesSkipsBinaryFiles(t *testing.T) {
	root := t.TempDir()
	binaryFile := testutil.WriteFile(t, root, "quill", "\x00binary\n")

	repository := profiles.RepositoryConfig()
	files, err := CollectAllFiles(
		repository.ResolveScopeRoots(root, style.Scope("all")),
		walkConfig(repository),
	)
	if err != nil {
		t.Fatalf("collect all files: %v", err)
	}

	if slices.Contains(files, binaryFile) {
		t.Fatalf("unexpected binary file %q in %v", binaryFile, files)
	}
}

func TestCollectFilesExcludesSymlinkLeafMatchingExtension(t *testing.T) {
	root := t.TempDir()
	regular := testutil.WriteFile(t, root, "kept.sh", "#!/bin/sh\necho hi\n")

	target := testutil.WriteFile(t, t.TempDir(), "secret.sh", "#!/bin/sh\necho secret\n")
	if err := os.Symlink(target, filepath.Join(root, "evil.sh")); err != nil {
		t.Skipf("symlink unsupported: %v", err)
	}

	files, err := CollectFiles([]string{root}, walkConfig(profiles.RepositoryConfig()), ".sh")
	if err != nil {
		t.Fatalf("CollectFiles: %v", err)
	}

	requirePaths(t, files, []string{regular})
}

func TestCollectAllFilesExcludesSymlinkLeaf(t *testing.T) {
	root := t.TempDir()
	regular := testutil.WriteFile(t, root, "kept.txt", "hello\n")

	target := testutil.WriteFile(t, t.TempDir(), "secret.txt", "secret\n")
	if err := os.Symlink(target, filepath.Join(root, "evil.txt")); err != nil {
		t.Skipf("symlink unsupported: %v", err)
	}

	files, err := CollectAllFiles([]string{root}, walkConfig(profiles.RepositoryConfig()))
	if err != nil {
		t.Fatalf("CollectAllFiles: %v", err)
	}

	requirePaths(t, files, []string{regular})
}

/* ---------------------------------------- Policy Checks --------------------------------------- */

func TestValidateCollectorPolicyAllowsConfiguredGeneratedMarker(t *testing.T) {
	repository := profiles.RepositoryConfig()
	repository.GeneratedMarker = "AUTOGENERATED"

	if err := ValidateCollectorPolicy(walkConfig(repository)); err != nil {
		t.Fatalf("ValidateCollectorPolicy(custom marker): %v", err)
	}
}

func requirePaths(t *testing.T, actual []string, expected []string) {
	t.Helper()

	if slices.Compare(actual, expected) != 0 {
		t.Fatalf("files = %v, expected %v", actual, expected)
	}
}

func walkConfig(repository profile.RepositoryConfig) (config WalkConfig) {
	return WalkConfig{
		ExcludedDirectories: repository.ExcludedDirectories,
		GeneratedMarker:     repository.GeneratedMarker,
	}
}
