package filewalk

import (
	"slices"
	"testing"

	"ciphera/tools/internal/contract"
	"ciphera/tools/internal/fixtures"
	"ciphera/tools/internal/fixtures/profiles"
)

/* --------------------------------------- File Collection -------------------------------------- */

func TestCollectFilesSkipsExcludedDirectoriesAndGeneratedFiles(t *testing.T) {
	repoRoot := t.TempDir()
	keptFile := fixtures.WriteFile(t, repoRoot, "internal/example/kept.go", "package example\n")
	testdataFile := fixtures.WriteFile(
		t,
		repoRoot,
		"testdata/example/skipped.go",
		"package example\n",
	)
	thirdPartyFile := fixtures.WriteFile(
		t,
		repoRoot,
		"third_party/example/skipped.go",
		"package example\n",
	)
	generatedFile := fixtures.WriteFile(
		t,
		repoRoot,
		"internal/example/generated.go",
		"// Code generated by tests. DO NOT EDIT.\npackage example\n",
	)

	files, err := CollectFiles(
		repoRoot,
		profiles.RepositoryConfig(t),
		contract.Scope("all"),
		".go",
	)
	if err != nil {
		t.Fatalf("collect files: %v", err)
	}

	if !slices.Contains(files, keptFile) {
		t.Fatalf("expected kept file %q in %v", keptFile, files)
	}

	for _, path := range files {
		switch path {
		case testdataFile, thirdPartyFile, generatedFile:
			t.Fatalf("unexpected excluded file %q in %v", path, files)
		}
	}
}

func TestCollectFilesKeepsProseMentionsOfGeneratedMarker(t *testing.T) {
	repoRoot := t.TempDir()
	markdownFile := fixtures.WriteFile(
		t,
		repoRoot,
		"STYLE.md",
		"# Style guide\n\n* Generated files that include `DO NOT EDIT.`\n",
	)

	files, err := CollectFiles(
		repoRoot,
		profiles.RepositoryConfig(t),
		contract.Scope("all"),
		".md",
	)
	if err != nil {
		t.Fatalf("collect markdown files: %v", err)
	}

	if !slices.Contains(files, markdownFile) {
		t.Fatalf("expected prose markdown file %q in %v", markdownFile, files)
	}
}

func TestCollectFilesInScopesDeduplicatesRoots(t *testing.T) {
	repoRoot := t.TempDir()
	commandFile := fixtures.WriteFile(t, repoRoot, "cmd/main.go", "package main\n")
	internalFile := fixtures.WriteFile(t, repoRoot, "internal/app.go", "package internal\n")
	toolsFile := fixtures.WriteFile(t, repoRoot, "tools/main.go", "package main\n")

	repository := profiles.RepositoryConfig(t)
	repository.ScopeRoots = map[contract.Scope][]string{
		"app":     {"cmd", "internal"},
		"command": {"cmd"},
		"tools":   {"tools"},
	}

	files, err := CollectFilesInScopes(
		repoRoot,
		repository,
		[]contract.Scope{"app", "command", "tools"},
		".go",
	)
	if err != nil {
		t.Fatalf("collect scoped files: %v", err)
	}

	requirePaths(t, files, []string{commandFile, internalFile, toolsFile})
}

func TestCollectAllFilesKeepsConfigMentionsOfGeneratedMarker(t *testing.T) {
	repoRoot := t.TempDir()
	configFile := fixtures.WriteFile(
		t,
		repoRoot,
		"style.toml",
		"generated_marker = \"DO NOT EDIT.\"\n",
	)

	files, err := CollectAllFiles(
		repoRoot,
		profiles.RepositoryConfig(t),
		contract.Scope("all"),
	)
	if err != nil {
		t.Fatalf("collect all files: %v", err)
	}

	if !slices.Contains(files, configFile) {
		t.Fatalf("expected config file %q in %v", configFile, files)
	}
}

/* ---------------------------------------- Policy Checks --------------------------------------- */

func TestValidateCollectorPolicyAllowsConfiguredGeneratedMarker(t *testing.T) {
	repository := profiles.RepositoryConfig(t)
	repository.GeneratedMarker = "AUTOGENERATED"

	if err := ValidateCollectorPolicy(repository); err != nil {
		t.Fatalf("ValidateCollectorPolicy(custom marker): %v", err)
	}
}

func requirePaths(t *testing.T, actual []string, expected []string) {
	t.Helper()

	if slices.Compare(actual, expected) != 0 {
		t.Fatalf("files = %v, expected %v", actual, expected)
	}
}
