package filewalk

import (
	"path/filepath"
	"slices"
	"testing"

	"ciphera/tools/internal/policy"
	"ciphera/tools/internal/style"
	"ciphera/tools/internal/testutil"
	"ciphera/tools/internal/testutil/profiles"
)

/* --------------------------------------- File Collection -------------------------------------- */

func TestCollectFilesSkipsExcludedDirectoriesAndGeneratedFiles(t *testing.T) {
	repoRoot := t.TempDir()
	keptFile := testutil.WriteFile(t, repoRoot, "internal/example/kept.go", "package example\n")
	testdataFile := testutil.WriteFile(
		t,
		repoRoot,
		"testdata/example/skipped.go",
		"package example\n",
	)
	thirdPartyFile := testutil.WriteFile(
		t,
		repoRoot,
		"third_party/example/skipped.go",
		"package example\n",
	)
	generatedFile := testutil.WriteFile(
		t,
		repoRoot,
		"internal/example/generated.go",
		"// Code generated by tests. DO NOT EDIT.\npackage example\n",
	)

	repository := profiles.RepositoryConfig(t)
	files, err := CollectFiles(
		repository.ResolveScopeRoots(repoRoot, style.Scope("all")),
		walkConfig(repository),
		".go",
	)
	if err != nil {
		t.Fatalf("collect files: %v", err)
	}

	if !slices.Contains(files, keptFile) {
		t.Fatalf("expected kept file %q in %v", keptFile, files)
	}

	for _, path := range files {
		switch path {
		case testdataFile, thirdPartyFile, generatedFile:
			t.Fatalf("unexpected excluded file %q in %v", path, files)
		}
	}
}

func TestCollectFilesKeepsProseMentionsOfGeneratedMarker(t *testing.T) {
	repoRoot := t.TempDir()
	markdownFile := testutil.WriteFile(
		t,
		repoRoot,
		"STYLE.md",
		"# Style guide\n\n* Generated files that include `DO NOT EDIT.`\n",
	)

	repository := profiles.RepositoryConfig(t)
	files, err := CollectFiles(
		repository.ResolveScopeRoots(repoRoot, style.Scope("all")),
		walkConfig(repository),
		".md",
	)
	if err != nil {
		t.Fatalf("collect markdown files: %v", err)
	}

	if !slices.Contains(files, markdownFile) {
		t.Fatalf("expected prose markdown file %q in %v", markdownFile, files)
	}
}

func TestCollectFilesInRootsDeduplicatesOverlappingRoots(t *testing.T) {
	repoRoot := t.TempDir()
	commandFile := testutil.WriteFile(t, repoRoot, "cmd/main.go", "package main\n")
	internalFile := testutil.WriteFile(t, repoRoot, "internal/app.go", "package internal\n")
	toolsFile := testutil.WriteFile(t, repoRoot, "tools/main.go", "package main\n")

	repository := profiles.RepositoryConfig(t)
	roots := []string{
		filepath.Join(repoRoot, "cmd"),
		filepath.Join(repoRoot, "internal"),
		filepath.Join(repoRoot, "tools"),
	}
	files, err := CollectFiles(roots, walkConfig(repository), ".go")
	if err != nil {
		t.Fatalf("collect scoped files: %v", err)
	}

	requirePaths(t, files, []string{commandFile, internalFile, toolsFile})
}

func TestCollectAllFilesKeepsConfigMentionsOfGeneratedMarker(t *testing.T) {
	repoRoot := t.TempDir()
	configFile := testutil.WriteFile(
		t,
		repoRoot,
		"style.toml",
		"generated_marker = \"DO NOT EDIT.\"\n",
	)

	repository := profiles.RepositoryConfig(t)
	files, err := CollectAllFiles(
		repository.ResolveScopeRoots(repoRoot, style.Scope("all")),
		walkConfig(repository),
	)
	if err != nil {
		t.Fatalf("collect all files: %v", err)
	}

	if !slices.Contains(files, configFile) {
		t.Fatalf("expected config file %q in %v", configFile, files)
	}
}

/* ---------------------------------------- Policy Checks --------------------------------------- */

func TestValidateCollectorPolicyAllowsConfiguredGeneratedMarker(t *testing.T) {
	repository := profiles.RepositoryConfig(t)
	repository.GeneratedMarker = "AUTOGENERATED"

	if err := ValidateCollectorPolicy(walkConfig(repository)); err != nil {
		t.Fatalf("ValidateCollectorPolicy(custom marker): %v", err)
	}
}

func requirePaths(t *testing.T, actual []string, expected []string) {
	t.Helper()

	if slices.Compare(actual, expected) != 0 {
		t.Fatalf("files = %v, expected %v", actual, expected)
	}
}

func walkConfig(repository policy.RepositoryConfig) (config WalkConfig) {
	return WalkConfig{
		ExcludedDirectories: repository.ExcludedDirectories,
		GeneratedMarker:     repository.GeneratedMarker,
	}
}
