package scenarios

import (
	"path/filepath"
	"testing"

	"ciphera/tools/internal/fixtures"
	"ciphera/tools/internal/fixtures/profiles"
	"ciphera/tools/internal/rules/golang"
)

func TestGoStyleRejectsMissingScanRoot(t *testing.T) {
	missingRoot := filepath.Join(t.TempDir(), "missing")

	if _, err := golang.CheckDirectories(
		fixtures.RepoRoot(t),
		[]string{missingRoot},
		profiles.Current(t),
	); err == nil {
		t.Fatal("expected missing scan root error")
	}
}

func TestGoStyleSkipsGeneratedFiles(t *testing.T) {
	tempDir := t.TempDir()
	writeSourceFile(
		t,
		filepath.Join(tempDir, "internal", "generated.go"),
		`// Code generated by test. DO NOT EDIT.
package internal

func Bad() string {
	return ""
}
`,
	)

	result, err := runGoStyleResult(t, tempDir)
	if err != nil {
		t.Fatalf("expected generated Go file to be skipped, diagnostics: %#v", result.Diagnostics)
	}
}
