package engine

import (
	"context"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strings"

	"github.com/wbd2023/quill/internal/profile"
)

/* ------------------------------------------ Constants ----------------------------------------- */

const (
	defaultPreset   = "minimal"
	styleFileName   = "STYLE.md"
	profileFileName = profile.DefaultFilename
)

const (
	configDirectoryPermission os.FileMode = 0o755
	configFilePermission      os.FileMode = 0o644
)

const (
	minimalRequirementSection = "1.1"
	minimalRequirementSlug    = "enforcement-levels"
	requirementIDToken        = "__REQUIREMENT_ID__"
)

const minimalStyleGuide = `# Style

This STYLE.md documents the requirements Quill enforces. Each requirement carries a stable
identifier that the Quill profile binds to an executable rule. Replace this file with your
repository's real style policy as it grows.

## 1. Repository policy

### 1.1 Enforcement levels

<!-- style: id=__REQUIREMENT_ID__ -->
* Every bound style rule declares its enforcement level so failures classify consistently.
`

const minimalProfile = `# Quill profile generated by ` + "`quill init --preset minimal`" + `.
#
# A minimal, immediately-valid starter built on the Shipped project Pack. Add scopes, Packs,
# Tools, and Rules as your repository grows. Inspect the active configuration with
# ` + "`quill list rules`" + ` and ` + "`quill explain rule:<id>`" + `.

schema_version = 1

[repository]
root_markers = ["STYLE.md", "quill.toml"]
default_scope = "all"
excluded_directories = [".git", "vendor"]
generated_marker = "DO NOT EDIT."

[repository.scope_roots]
all = ["."]

[style_guide]
path = "STYLE.md"

[packs]
enabled = ["project"]

# The project Pack requires a quality-command surface. Declare the Make targets your repository
# exposes; Quill validates them only when you bind the profile/quality-commands rule.
[packs.project.commands]
runner = "make"
path = "Makefile"

[[packs.project.commands.required_targets]]
name = "build"
recipe_line = "go build ./..."

# The project Pack references these tools, so each must be pinned. The bound rule below needs none
# of them, so ` + "`quill check`" + ` passes before they are installed.
[tools.go]
version = "1.24.5"

[tools.goimports]
version = "v0.42.0"

[tools.misspell]
version = "v0.3.4"

[tools."golangci-lint"]
version = "v2.6.2"

[tools.shfmt]
version = "v3.12.0"

[tools.shellcheck]
version = "0.10.0"

[tools.markdownlint]
version = "0.45.0"

[[rules]]
id = "profile/enforcement-levels"
enforcement = "required"
scope = "all"
requirement_ids = ["__REQUIREMENT_ID__"]
`

/* -------------------------------------------- Types ------------------------------------------- */

// InitResult describes the repository initialised by Init.
type InitResult struct {
	Root   string
	Preset string
}

type initPresetContent struct {
	styleGuide string
	profile    string
}

/* --------------------------------------- Initialisation --------------------------------------- */

// Init creates a new Quill policy in root from preset. It never overwrites either policy file,
// refuses symlinked destinations, and rolls back STYLE.md when quill.toml cannot be created.
func Init(
	ctx context.Context,
	root string,
	presetName string,
) (result InitResult, err error) {
	if err := ctx.Err(); err != nil {
		return InitResult{}, err
	}

	preset, ok := initPreset(presetName)
	if !ok {
		return InitResult{}, newArgumentError("unsupported preset %q", presetName)
	}

	stylePath := filepath.Join(root, styleFileName)
	profilePath := filepath.Join(root, profileFileName)
	occupied, err := occupiedPolicyFiles(stylePath, profilePath)
	if err != nil {
		return InitResult{}, fmt.Errorf("check target directory %q: %w", root, err)
	}

	if len(occupied) > 0 {
		return InitResult{}, fmt.Errorf(
			"refusing to overwrite existing policy files in %q: %s already present",
			root,
			strings.Join(occupied, " and "),
		)
	}

	if err := ctx.Err(); err != nil {
		return InitResult{}, err
	}

	if err := os.MkdirAll(root, configDirectoryPermission); err != nil {
		return InitResult{}, fmt.Errorf("create target directory %q: %w", root, err)
	}

	if err := writePolicyFiles(
		ctx, stylePath, profilePath,
		preset.styleGuide, preset.profile,
	); err != nil {
		return InitResult{}, fmt.Errorf("write policy files in %q: %w", root, err)
	}

	return InitResult{Root: root, Preset: presetName}, nil
}

/* ------------------------------------------- Helpers ------------------------------------------ */

// occupiedPolicyFiles returns the base names of any policy file paths that already name an entry.
// It uses Lstat so it does not follow symlinks: a dangling or valid symlink at a policy path
// counts as occupied and is refused, preventing Init from writing through an attacker-controlled
// link. The returned names let Init report exactly which file prevented creation.
func occupiedPolicyFiles(paths ...string) (occupied []string, err error) {
	for _, path := range paths {
		switch _, statErr := os.Lstat(path); {
		case statErr == nil:
			occupied = append(occupied, filepath.Base(path))
		case errors.Is(statErr, fs.ErrNotExist):
			continue
		default:
			return nil, statErr
		}
	}

	return occupied, nil
}

// writePolicyFiles writes STYLE.md then quill.toml. Each file is created with an exclusive,
// non-clobbering open, so a file that appears between the occupancy check and the write fails
// instead of being truncated. If quill.toml cannot be written, STYLE.md is removed so Init never
// leaves a half-initialised repository.
func writePolicyFiles(
	ctx context.Context,
	stylePath string,
	profilePath string,
	styleGuide string,
	profileContents string,
) (err error) {
	if err := ctx.Err(); err != nil {
		return err
	}

	if err := writeExclusive(stylePath, styleGuide); err != nil {
		return fmt.Errorf("write %s: %w", styleFileName, err)
	}

	if err := ctx.Err(); err != nil {
		_ = os.Remove(stylePath)
		return err
	}

	if err := writeExclusive(profilePath, profileContents); err != nil {
		_ = os.Remove(stylePath)
		return fmt.Errorf("write %s: %w", profileFileName, err)
	}

	return nil
}

// writeExclusive atomically creates path containing contents with an exclusive open. It fails if
// path already exists and never truncates an existing file.
func writeExclusive(path string, contents string) (err error) {
	file, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_EXCL, configFilePermission)
	if err != nil {
		return err
	}

	defer func() {
		if closeErr := file.Close(); err == nil {
			err = closeErr
		}
	}()

	if _, err = file.WriteString(contents); err != nil {
		return err
	}

	return nil
}

func minimalRequirementID() (id string) {
	return minimalRequirementSection + "." + minimalRequirementSlug
}

func initPreset(name string) (content initPresetContent, ok bool) {
	if name != defaultPreset {
		return initPresetContent{}, false
	}

	requirementID := minimalRequirementID()
	return initPresetContent{
		styleGuide: strings.ReplaceAll(minimalStyleGuide, requirementIDToken, requirementID),
		profile:    strings.ReplaceAll(minimalProfile, requirementIDToken, requirementID),
	}, true
}
