package toml_test

import (
	"testing"

	"github.com/wbd2023/Quill/internal/policy"
	"github.com/wbd2023/Quill/internal/profile/toml"
	"github.com/wbd2023/Quill/internal/style"
	"github.com/wbd2023/Quill/internal/testutil"
)

func TestEncodeRoundTripsLocalProfile(t *testing.T) {
	t.Parallel()

	config := policy.Config{
		SchemaVersion: policy.SchemaVersion,
		Repository: policy.RepositoryConfig{
			RootMarkers: []string{"PROJECT.marker"},
			ScopeRoots: map[style.Scope][]string{
				style.Scope("app"): {"."},
			},
			DefaultScope:        style.Scope("app"),
			ExcludedDirectories: []string{"vendor/"},
			GeneratedMarker:     "Code generated by",
		},
		StyleGuide: policy.StyleGuideConfig{
			Path: "STYLE.md",
		},
		PathRoles: policy.PathRoles{
			"go_source": {"internal/"},
		},
		FileSets: policy.FileSets{
			{
				Name: "go",
				Include: policy.FileSetInclude{
					Extensions: []string{".go"},
					Paths: map[style.Scope][]string{
						style.Scope("app"): {"internal/"},
					},
				},
			},
		},
		Tools: policy.PinnedTools{
			{ID: "go", Version: "1.0.0"},
		},
		EnabledPacks: []string{"go"},
		Rules: []policy.RuleBinding{
			{
				RuleID:         "go/test",
				Enforcement:    style.EnforcementRequired,
				Scope:          style.Scope("app"),
				RequirementIDs: []string{"1.1.test-rule"},
			},
		},
	}

	contents, err := toml.Encode(config)
	if err != nil {
		t.Fatalf("Encode: %v", err)
	}

	got, err := toml.Decode(contents)
	if err != nil {
		t.Fatalf("Decode encoded profile: %v", err)
	}

	requireConfigEqual(t, config, got)
}

func TestEncodeRoundTripsCurrentProfile(t *testing.T) {
	t.Parallel()

	source := testutil.ReadFile(t, testutil.RepositoryRoot(t), "quill.toml")
	config, err := toml.Decode(source)
	if err != nil {
		t.Fatalf("Decode: %v", err)
	}

	contents, err := toml.Encode(config)
	if err != nil {
		t.Fatalf("Encode: %v", err)
	}

	got, err := toml.Decode(contents)
	if err != nil {
		t.Fatalf("Decode encoded profile: %v", err)
	}

	requireConfigEqual(t, config, got)
}
