package scripts_test

/* ---------------------------------------- Registry Rows --------------------------------------- */

func expectedStyleRegistryRows() (rows []styleRegistryRow) {
	rows = []styleRegistryRow{
		newStyleRegistryRow(
			registryTierOne,
			registryLevelRequired,
			"1-2",
			"golangci-lint (app)",
			registryScopeApp,
			registryRunnerExecutor,
			registryTargetGolangciApp,
		),
		newStyleRegistryRow(
			registryTierOne,
			registryLevelRequired,
			"1-2",
			"golangci-lint (tools/stylecheck)",
			registryScopeTools,
			registryRunnerExecutor,
			registryTargetGolangciTools,
		),
		newStyleRegistryRow(
			registryTierTwo,
			registryLevelRequired,
			"1.1",
			"Line length (Go)",
			registryScopeAll,
			registryRunnerScriptScope,
			checkPathGoLineLength,
		),
		newStyleRegistryRow(
			registryTierTwo,
			registryLevelRequired,
			"1.1",
			"Line length (Bash scripts)",
			registryScopeAll,
			registryRunnerScriptScope,
			checkPathBashLineLength,
		),
		newStyleRegistryRow(
			registryTierTwo,
			registryLevelRequired,
			"1.2",
			"Language spelling (non-Go, UK locale)",
			registryScopeAll,
			registryRunnerScriptScope,
			checkPathGeneralSpelling,
		),
		newStyleRegistryRow(
			registryTierTwo,
			registryLevelRequired,
			"3.2",
			"Markdown style (markdownlint)",
			registryScopeAll,
			registryRunnerScriptScope,
			checkPathGeneralMarkdown,
		),
		newStyleRegistryRow(
			registryTierTwo,
			registryLevelRequired,
			"1.3",
			"Architecture imports",
			registryScopeApp,
			registryRunnerScript,
			checkPathGoArchitecture,
		),
		newStyleRegistryRow(
			registryTierTwo,
			registryLevelRequired,
			"1.4",
			"ASCII-only characters",
			registryScopeAll,
			registryRunnerScriptScope,
			checkPathGeneralASCII,
		),
		newStyleRegistryRow(
			registryTierTwo,
			registryLevelRequired,
			"2.2",
			"Naming conventions",
			registryScopeAll,
			registryRunnerScriptScope,
			checkPathGeneralNaming,
		),
		newStyleRegistryRow(
			registryTierTwo,
			registryLevelRequired,
			"2.4",
			"Section header format",
			registryScopeAll,
			registryRunnerScriptScope,
			checkPathGeneralHeaders,
		),
		newStyleRegistryRow(
			registryTierTwo,
			registryLevelRequired,
			"2.10",
			"No magic values (Go)",
			registryScopeAll,
			registryRunnerScriptScope,
			checkPathGoMagicValues,
		),
		newStyleRegistryRow(
			registryTierTwo,
			registryLevelRequired,
			"2.11",
			"Bash script style",
			registryScopeAll,
			registryRunnerScriptScope,
			checkPathBashStyle,
		),
		newStyleRegistryRow(
			registryTierTwo,
			registryLevelRequired,
			"2.11",
			"Bash static analysis (shellcheck)",
			registryScopeAll,
			registryRunnerScriptScope,
			checkPathBashShellcheck,
		),
		newStyleRegistryRow(
			registryTierTwo,
			registryLevelRequired,
			"2.11",
			"Bash formatting (shfmt)",
			registryScopeAll,
			registryRunnerScriptScope,
			checkPathBashShfmt,
		),
		newStyleRegistryRow(
			registryTierTwo,
			registryLevelRecommendation,
			"R2.10",
			"Magic values (Bash)",
			registryScopeAll,
			registryRunnerScriptScope,
			checkPathBashMagicValues,
		),
		newStyleRegistryRow(
			registryTierTwo,
			registryLevelRecommendation,
			"R2.12",
			"Guard-clause spacing (Go)",
			registryScopeAll,
			registryRunnerScriptScope,
			checkPathGoVerticalSpacing,
		),
		newStyleRegistryRow(
			registryTierThree,
			registryLevelRequired,
			"2.2+",
			"AST rules (app)",
			registryScopeApp,
			registryRunnerExecutor,
			registryTargetASTApp,
		),
		newStyleRegistryRow(
			registryTierThree,
			registryLevelRequired,
			"2.2+",
			"AST rules (tools/stylecheck)",
			registryScopeTools,
			registryRunnerExecutor,
			registryTargetASTTools,
		),
	}

	return rows
}
