package profile_test

import (
	"os"
	"testing"

	"github.com/google/go-cmp/cmp"

	"ciphera/tools/internal/contract"
	"ciphera/tools/internal/policy"
	"ciphera/tools/internal/profile"
	"ciphera/tools/internal/requirementid"
)

func TestFormatReturnsCanonicalTOML(t *testing.T) {
	t.Parallel()

	contents, err := profile.Format(policy.Config{
		SchemaVersion: policy.SchemaVersion,
		Repository: policy.RepositoryConfig{
			RootMarkers: []string{"PROJECT.marker"},
			ScopeRoots: map[contract.Scope][]string{
				contract.Scope("app"): {"."},
			},
			DefaultScope:    contract.Scope("app"),
			GeneratedMarker: "Code generated by",
		},
		StyleGuide: policy.StyleGuideConfig{
			Path:     "STYLE.md",
			IDScheme: requirementid.SectionSlug,
		},
		EnabledPacks: []string{"project", "text"},
		PackConfigs: policy.PackConfigs{
			"project": policy.PackConfig{
				"commands": map[string]any{
					"runner": "make",
					"path":   "Makefile",
					"required_targets": []map[string]any{
						{"name": "lint", "recipe_line": "go test ./..."},
					},
				},
			},
			"text": policy.PackConfig{
				"section_headers": map[string]any{
					"large_min_lines":  100,
					"short_max_lines":  79,
					"max_header_count": 6,
					"generic_names":    []string{"Misc"},
					"structural_names": []string{},
				},
			},
		},
		Rules: []policy.RuleBinding{
			{
				RuleID:         "text/test",
				Enforcement:    contract.EnforcementRequired,
				Scope:          contract.Scope("app"),
				RequirementIDs: []string{"1.1.test-rule"},
			},
		},
	})
	if err != nil {
		t.Fatalf("Format: %v", err)
	}

	expected, err := os.ReadFile("testdata/format.golden.toml")
	if err != nil {
		t.Fatalf("ReadFile: %v", err)
	}

	if diff := cmp.Diff(string(expected), contents); diff != "" {
		t.Fatalf("canonical TOML mismatch (-expected +actual):\n%s", diff)
	}
}

func TestFormatValidatesProfile(t *testing.T) {
	t.Parallel()

	_, err := profile.Format(policy.Config{SchemaVersion: 2})
	requireErrorContains(t, err, "version 2")
}
