package profile

import (
	"strings"
	"testing"

	"github.com/wbd2023/quill/internal/style"
	"github.com/wbd2023/quill/internal/testutil"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
)

func requireTOMLEqual[T any](t *testing.T, name string, expected T, actual T) {
	t.Helper()

	if diff := cmp.Diff(expected, actual); diff != "" {
		t.Fatalf("%s mismatch (-expected +actual):\n%s", name, diff)
	}
}

func requireConfigEqual(t *testing.T, expected Profile, actual Profile) {
	t.Helper()

	if diff := cmp.Diff(expected, actual, cmpopts.EquateEmpty()); diff != "" {
		t.Fatalf("config mismatch (-expected +actual):\n%s", diff)
	}
}

func TestDecodeReadsMultilineArrays(t *testing.T) {
	t.Parallel()

	config, err := decodeTOML(`schema_version = 1

[path_roles]
go_source = [
	"cmd/",
	"internal/",
]
`)
	if err != nil {
		t.Fatalf("Decode: %v", err)
	}

	requireTOMLEqual(t, "path_roles", PathRoles{
		"go_source": {"cmd/", "internal/"},
	}, config.PathRoles)
}

func TestDecodeReadsTargetWorkingDirectory(t *testing.T) {
	t.Parallel()

	config, err := decodeTOML(`schema_version = 1

[targets.tools_go]
language = "go"
scope = "tools"
working_directory = "tools"
`)
	if err != nil {
		t.Fatalf("Decode: %v", err)
	}

	target, found := config.Targets.Lookup("tools_go")
	if !found {
		t.Fatal("expected tools_go target")
	}

	if target.WorkingDirectory != "tools" {
		t.Fatalf("working dir = %q", target.WorkingDirectory)
	}
}

func TestDecodeRejectsUnknownKeys(t *testing.T) {
	t.Parallel()

	_, err := decodeTOML(`schema_version = 1
unknown_key = true
`)
	if err == nil {
		t.Fatal("expected unknown key to fail")
	}
}

func TestDecodeRejectsOldKeys(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name  string
		input string
	}{
		{
			name:  "profile version",
			input: "profile_version = 1\n",
		},
		{
			name: "rule level",
			input: `schema_version = 1

[[rules]]
id = "text/ascii"
level = "required"
scope = "all"
requirement_ids = ["0.1.example"]
`,
		},
		{
			name: "target workdir",
			input: `schema_version = 1

[targets.tools_go]
language = "go"
scope = "tools"
workdir = "tools"
`,
		},
		{
			name: "repository scan roots",
			input: `schema_version = 1

[repository]
app_scan_roots = ["cmd"]
`,
		},
		{
			name: "styleguide table",
			input: `schema_version = 1

[styleguide]
path = "STYLE.md"
`,
		},
		{
			name: "file set excluded names",
			input: `schema_version = 1

[file_sets.spelling]
excluded_names = ["LICENSE"]
`,
		},
		{
			name: "file set excluded name prefixes",
			input: `schema_version = 1

[file_sets.spelling]
excluded_name_prefixes = ["LICENSE."]
`,
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			t.Parallel()

			_, err := decodeTOML(test.input)
			if err == nil {
				t.Fatal("expected old key to fail")
			}
		})
	}
}

func TestDecodeReadsPackPolicies(t *testing.T) {
	t.Parallel()

	config, err := decodeTOML(`schema_version = 1

[packs]
enabled = ["go"]

[packs.go]
local_import_prefixes = ["ciphera"]

[packs.go.parameters]
secret_names = ["token"]
`)
	if err != nil {
		t.Fatalf("Decode: %v", err)
	}

	policy, found := config.PackPolicies.Lookup("go")
	if !found {
		t.Fatal("expected Go Pack Policy")
	}

	parameters, ok := policy["parameters"].(map[string]any)
	if !ok {
		t.Fatalf("expected parameters map, got %T", policy["parameters"])
	}

	requireTOMLEqual(t, "pack parameters", map[string]any{
		"secret_names": []any{"token"},
	}, parameters)
}

func TestDecodeReadsEmptyPackPolicy(t *testing.T) {
	t.Parallel()

	config, err := decodeTOML(`schema_version = 1

[packs]
enabled = ["external"]

[packs.external]
`)
	if err != nil {
		t.Fatalf("decodeTOML: %v", err)
	}

	policy, found := config.PackPolicies.Lookup("external")
	if !found {
		t.Fatal("expected empty Pack Policy to be retained")
	}
	if len(policy) != 0 {
		t.Fatalf("empty Pack Policy = %#v", policy)
	}
}

func TestDecodeRejectsNonTablePackPolicy(t *testing.T) {
	t.Parallel()

	_, err := decodeTOML(`schema_version = 1

[packs]
enabled = ["go"]
go = "invalid"
`)
	if err == nil || !strings.Contains(err.Error(), "packs.go policy must be a table") {
		t.Fatalf("expected Pack Policy table error, got %v", err)
	}
}

func TestEncodeRoundTripsLocalProfile(t *testing.T) {
	t.Parallel()

	config := Profile{
		SchemaVersion: SchemaVersion,
		Repository: RepositoryConfig{
			RootMarkers: []string{"PROJECT.marker"},
			ScopeRoots: map[style.Scope][]string{
				style.Scope("app"): {"."},
			},
			DefaultScope:        style.Scope("app"),
			ExcludedDirectories: []string{"vendor/"},
			GeneratedMarker:     "Code generated by",
		},
		StyleGuide: StyleGuideConfig{
			Path: "STYLE.md",
		},
		PathRoles: PathRoles{
			"go_source": {"internal/"},
		},
		FileSets: FileSets{
			{
				Name: "go",
				Include: FileSetInclude{
					Extensions: []string{".go"},
					Paths: map[style.Scope][]string{
						style.Scope("app"): {"internal/"},
					},
				},
			},
		},
		Tools: PinnedTools{
			{ID: "go", Version: "1.0.0"},
		},
		EnabledPacks: []string{"go"},
		Rules: []RuleBinding{
			{
				RuleID:         "go/test",
				Enforcement:    style.EnforcementRequired,
				Scope:          style.Scope("app"),
				RequirementIDs: []string{"1.1.test-rule"},
			},
		},
	}

	contents, err := encodeTOML(config)
	if err != nil {
		t.Fatalf("Encode: %v", err)
	}

	got, err := decodeTOML(contents)
	if err != nil {
		t.Fatalf("Decode encoded profile: %v", err)
	}

	requireConfigEqual(t, config, got)
}

func TestEncodeRoundTripsCurrentProfile(t *testing.T) {
	t.Parallel()

	source := testutil.ReadFile(t, testutil.RepositoryRoot(t), "quill.toml")
	config, err := decodeTOML(source)
	if err != nil {
		t.Fatalf("Decode: %v", err)
	}

	contents, err := encodeTOML(config)
	if err != nil {
		t.Fatalf("Encode: %v", err)
	}

	got, err := decodeTOML(contents)
	if err != nil {
		t.Fatalf("Decode encoded profile: %v", err)
	}

	requireConfigEqual(t, config, got)
}
