package profiletest

import (
	"ciphera/tools/internal/policy"
	"ciphera/tools/internal/style"
)

// Config returns a valid minimal profile config fixture.
func Config() (config policy.Config) {
	return policy.Config{
		SchemaVersion: policy.SchemaVersion,
		Repository:    baselineRepository(),
		StyleGuide: policy.StyleGuideConfig{
			Path:     "STYLE.md",
			IDScheme: style.SectionSlug,
		},
		PathRoles: policy.PathRoles{
			PathRole: {"internal/"},
		},
		FileSets:     baselineFileSets(),
		Targets:      baselineTargets(),
		Tools:        baselineTools(),
		EnabledPacks: []string{"test"},
		Rules: []policy.RuleBinding{
			{
				RuleID:         Rule,
				Enforcement:    style.EnforcementRequired,
				Scope:          Scope,
				RequirementIDs: []string{Requirement},
			},
		},
	}
}

func baselineRepository() (repository policy.RepositoryConfig) {
	return policy.RepositoryConfig{
		RootMarkers: []string{
			"PROJECT.marker",
		},
		ScopeRoots: map[style.Scope][]string{
			Scope: {"."},
		},
		DefaultScope:    Scope,
		GeneratedMarker: "Code generated by",
	}
}

func baselineFileSets() (fileSets policy.FileSets) {
	return append(fileSets, policy.FileSetConfig{
		Name: FileSet,
		Include: policy.FileSetInclude{
			Extensions: []string{".go"},
			Paths: map[style.Scope][]string{
				Scope: {"internal/"},
			},
		},
	})
}

func baselineTargets() (targets policy.TargetConfigs) {
	return append(targets,
		policy.TargetConfig{
			Name:        Target,
			Language:    Language,
			Scope:       Scope,
			FormatPaths: []string{"."},
			CheckPaths:  []string{"."},
		},
		policy.TargetConfig{
			Name:        OtherTarget,
			Language:    Language,
			Scope:       Scope,
			FormatPaths: []string{"."},
			CheckPaths:  []string{"."},
		},
	)
}

func baselineTools() (tools policy.PinnedTools) {
	return append(tools, policy.PinnedTool{ID: Tool, Version: "1.0.0"})
}
