package profiletest

import (
	"github.com/wbd2023/quill/internal/profile"
	"github.com/wbd2023/quill/internal/style"
)

// Config returns a valid minimal profile config fixture.
func Config() (config profile.Profile) {
	return profile.Profile{
		SchemaVersion: profile.SchemaVersion,
		Repository:    baselineRepository(),
		StyleGuide: profile.StyleGuideConfig{
			Path: "STYLE.md",
		},
		PathRoles: profile.PathRoles{
			PathRole: {"internal/"},
		},
		FileSets:     baselineFileSets(),
		Targets:      baselineTargets(),
		Tools:        baselineTools(),
		EnabledPacks: []string{"test"},
		Rules: []profile.RuleBinding{
			{
				RuleID:         Rule,
				Enforcement:    style.EnforcementRequired,
				Scope:          Scope,
				RequirementIDs: []string{Requirement},
			},
		},
	}
}

func baselineRepository() (repository profile.RepositoryConfig) {
	return profile.RepositoryConfig{
		RootMarkers: []string{
			"PROJECT.marker",
		},
		ScopeRoots: map[style.Scope][]string{
			Scope: {"."},
		},
		DefaultScope:    Scope,
		GeneratedMarker: "Code generated by",
	}
}

func baselineFileSets() (fileSets profile.FileSets) {
	return append(fileSets, profile.FileSetConfig{
		Name: FileSet,
		Include: profile.FileSetInclude{
			Extensions: []string{".go"},
			Paths: map[style.Scope][]string{
				Scope: {"internal/"},
			},
		},
	})
}

func baselineTargets() (targets profile.TargetConfigs) {
	return append(targets,
		profile.TargetConfig{
			Name:        Target,
			Language:    Language,
			Scope:       Scope,
			FormatPaths: []string{"."},
			CheckPaths:  []string{"."},
		},
		profile.TargetConfig{
			Name:        OtherTarget,
			Language:    Language,
			Scope:       Scope,
			FormatPaths: []string{"."},
			CheckPaths:  []string{"."},
		},
	)
}

func baselineTools() (tools profile.PinnedTools) {
	return append(tools, profile.PinnedTool{ID: Tool, Version: "1.0.0"})
}
