package checks

/* -------------------------------------- Diagnostic Codes -------------------------------------- */

const (
	DiagnosticAdapterWrapsCause         = "go/errors/adapter-wraps-cause"
	DiagnosticConstructorCategoryOrder  = "go/constructors/category-order"
	DiagnosticContextFirst              = "go/parameters/context-first"
	DiagnosticCryptoRand                = "go/security/crypto-rand"
	DiagnosticCRUDLOrder                = "go/order/crudl"
	DiagnosticDomainErrorsLocation      = "go/errors/domain-location"
	DiagnosticErrorContextLowercase     = "go/errors/context-lowercase"
	DiagnosticErrorContextNoPunctuation = "go/errors/context-no-punctuation"
	DiagnosticErrorContextNoSecrets     = "go/errors/context-no-secrets"
	DiagnosticExplicitNetworkTimeouts   = "go/resources/network-timeouts"
	DiagnosticFileOrder                 = "go/order/file"
	DiagnosticHelpersCallHelper         = "go/tests/helpers-call-helper"
	DiagnosticIgnoredCloseErrorReason   = "go/resources/close-error-reason"
	DiagnosticImplementationOrder       = "go/order/implementation-methods"
	DiagnosticInlineCommentLowercase    = "go/comments/inline-lowercase"
	DiagnosticInlineCommentNoPeriod     = "go/comments/inline-no-period"
	DiagnosticInterfaceValuesDirect     = "go/data/interface-values-direct"
	DiagnosticLenForSliceEmptiness      = "go/data/len-for-slice-emptiness"
	DiagnosticMockOrder                 = "go/order/mock-methods"
	DiagnosticNamedReturnValues         = "go/returns/named-values"
	DiagnosticNamedStructLiterals       = "go/data/named-struct-literals"
	DiagnosticNoContextOnStructs        = "go/resources/no-context-on-structs"
	DiagnosticNoDeprecatedCrypto        = "go/security/no-deprecated-crypto"
	DiagnosticNoDirectDomainCasts       = "go/domain/no-direct-casts"
	DiagnosticNoNakedReturns            = "go/returns/no-naked-returns"
	DiagnosticNoPlaceholderReturnNames  = "go/returns/no-placeholder-names"
	DiagnosticNoPointersToInterfaces    = "go/data/no-pointers-to-interfaces"
	DiagnosticNoSecretsInLogs           = "go/logging/no-secrets"
	DiagnosticNoSecretsInRepository     = "go/security/no-secrets-in-repository"
	DiagnosticNoShellInterpolation      = "go/process/no-shell-interpolation"
	DiagnosticNoTypeElision             = "go/parameters/no-type-elision"
	DiagnosticSecretsLast               = "go/parameters/secrets-last"
	DiagnosticSingleLetterNames         = "go/naming/single-letter-names"
	DiagnosticStableLogKeys             = "go/logging/stable-keys"
	DiagnosticStructuredLogs            = "go/logging/structured"
	DiagnosticTestAvoidArbitrarySleeps  = "go/tests/avoid-arbitrary-sleeps"
	DiagnosticTestSetenv                = "go/tests/use-setenv"
	DiagnosticTestTempDir               = "go/tests/use-tempdir"
)
